version: "3.8"

services:
  mysqldb:
    image: mysql:8.3.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=claro_db
    ports:
      - 3306:3306

  app:
    depends_on:
      - mysqldb
    build: .
    ports:
      - 8080:8080

